apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: posts.com
      http:
        paths: 
          - path: /posts/create
            backend:
              serviceName: post-service-cip
              servicePort: 4000
          - path: /
            backend:
              serviceName: frontend-service
              servicePort: 3000
          - path: /posts
            backend:
              serviceName: query-service
              servicePort: 4002